version: "3.8"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: RootDock@SQL
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    hostname: blahblah
    volumes:
      - ./src/main/resources/sql/table_setup.sql:/script/table_setup.sql:ro
    command: "--init-file /script/table_setup.sql"
    networks:
      - local_bridge

  bizexpense:
    image: bizexpense_image
    ports:
      - "8080:8080"
    environment:
      HOSTNAME: blahblah
    depends_on:
      db:
        condition: service_healthy
    networks:
      - local_bridge

networks:
  local_bridge:
#    driver: bridge